version: "3.8"

services:
  app:
    build:
      context: .
      args:
        CLONE_URL: ${CLONE_URL}
        INTERNAL_PORT: ${INTERNAL_PORT}
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    restart: always
